name: 定时运行

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-get-updatelog-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run Python script
      id: run-python-script
      run: python getACEupdatelog.py

    - name: Check for changes
      id: check-changes
      run: |
        git add .
        git diff --cached --quiet || echo "Changes detected"

    - name: Commit and push changes if any
      if: steps.check-changes.outputs.changes_detected != ''
      run: |
        git config user.name "YIShengJunn"
        git config user.email "LZY916127@outlook.com"
        git commit -m "updated"
        git push